In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:/Users/tinch/coderhouse/template/data/processed/dataset_merged_processed_cod.csv")

In [5]:
df.head(3)

,ID,systolic,relaxation,Cholesterol,triglyceride,HDL,LDL,age,height(cm),weight(kg),...,ALT,Gtp,dental caries,eyesight(left),eyesight(right),hearing(left),hearing(right),target,gender_M,tartar_Y
0,0,4.750000,3.041667,8.958333,3.416667,3.041667,5.250000,40.0,155.0,60.0,...,0.791667,1.125000,0,0.043056,0.041667,0.041667,0.041667,0,0,1
1,1,4.958333,2.916667,8.000000,4.791667,1.750000,5.291667,40.0,160.0,60.0,...,0.791667,0.750000,0,0.005556,0.004167,0.041667,0.041667,0,0,1
2,2,5.750000,3.583333,10.083333,7.583333,2.291667,6.291667,55.0,170.0,60.0,...,0.666667,0.916667,0,0.005556,0.005556,0.041667,0.041667,1,1,0

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   50000 non-null  int64
 1   systolic             50000 non-null  float64
 2   relaxation           50000 non-null  float64
 3   Cholesterol          50000 non-null  float64
 4   triglyceride         50000 non-null  float64
 5   HDL                  50000 non-null  float64
 6   LDL                  50000 non-null  float64
 7   age                  50000 non-null  float64
 8   height(cm)           50000 non-null  float64
 9   weight(kg)           50000 non-null  float64
 10  waist(cm)            50000 non-null  float64
 11  fasting blood sugar  50000 non-null  float64
 12  hemoglobin           50000 non-null  float64
 13  Urine protein        50000 non-null  float64
 14  serum creatinine     50000 non-null  float64
 15  ALT                  50000 non-null  float64
 16  Gtp                  50000 non-null  float64
 17  dental caries        50000 non-null  int64
 18  eyesight(left)       50000 non-null  float64
 19  eyesight(right)      50000 non-null  float64
 20  hearing(left)        50000 non-null  float64
 21  hearing(right)       50000 non-null  float64
 22  target               50000 non-null  int64
 23  gender_M             50000 non-null  int64
 24  tartar_Y             50000 non-null  int64
dtypes: float64(20), int64(5)
memory usage: 9.5 MB

In [10]:
X = df.drop(columns=["target", "ID"])
y = df["target"]

In [11]:
X

,systolic,relaxation,Cholesterol,triglyceride,HDL,LDL,age,height(cm),weight(kg),waist(cm),...,serum creatinine,ALT,Gtp,dental caries,eyesight(left),eyesight(right),hearing(left),hearing(right),gender_M,tartar_Y
0,4.750000,3.041667,8.958333,3.416667,3.041667,5.250000,40.0,155.0,60.0,3.377083,...,0.004861,0.791667,1.125000,0,0.043056,0.041667,0.041667,0.041667,0,1
1,4.958333,2.916667,8.000000,4.791667,1.750000,5.291667,40.0,160.0,60.0,3.375000,...,0.004167,0.791667,0.750000,0,0.005556,0.004167,0.041667,0.041667,0,1
2,5.750000,3.583333,10.083333,7.583333,2.291667,6.291667,55.0,170.0,60.0,3.333333,...,0.041667,0.666667,0.916667,0,0.005556,0.005556,0.041667,0.041667,1,0
3,4.166667,2.500000,13.416667,10.583333,1.875000,9.416667,40.0,165.0,70.0,3.666667,...,0.041667,1.083333,0.750000,0,0.045139,0.045139,0.041667,0.041667,1,1
4,5.000000,3.083333,7.666667,3.083333,2.583333,4.458333,40.0,155.0,60.0,3.583333,...,0.004167,0.583333,0.916667,0,0.041667,0.041667,0.041667,0.041667,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,5.062688,3.167519,8.206039,5.275309,2.625000,3.041667,50.0,160.0,55.0,2.961806,...,0.018823,1.128868,0.916667,0,0.004861,0.005556,0.041667,0.042758,1,1
49996,5.062688,3.167519,8.206039,5.275309,2.250000,3.208333,30.0,170.0,70.0,3.333333,...,0.018823,1.128868,0.750000,1,0.045139,0.041667,0.041667,0.042758,1,1
49997,5.062688,3.167519,8.206039,5.275309,1.958333,2.208333,20.0,165.0,65.0,3.541667,...,0.018823,1.128868,2.916667,0,0.045139,0.045139,0.041667,0.042758,1,1
49998,5.062688,3.167519,8.206039,5.275309,2.583333,4.125000,60.0,160.0,45.0,2.961806,...,0.018823,1.128868,1.041667,1,0.002778,0.002778,0.041667,0.042758,0,1
49999,5.062688,3.167519,8.206039,5.275309,2.750000,5.041667,45.0,170.0,80.0,4.000000,...,0.018823,1.128868,2.583333,1,0.045139,0.041667,0.041667,0.042758,1,0

In [12]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42, stratify=y)

In [22]:
y_train.value_counts(normalize=True)*100

target
0    63.342857
1    36.657143
Name: proportion, dtype: float64

In [23]:
y_test.value_counts(normalize=True)*100

target
0    63.34
1    36.66
Name: proportion, dtype: float64

### Entrenamiento y evaluacion de modelos

#### Arbol de Decision

In [24]:
from sklearn.tree import DecisionTreeClassifier

In [49]:
decision_tree = DecisionTreeClassifier(max_depth=4, random_state=42)

In [50]:
%%time
decision_tree.fit(X_train, y_train)

CPU times: total: 141 ms
Wall time: 140 ms

DecisionTreeClassifier(max_depth=4, random_state=42)

In [51]:
y_pred_train_dt = decision_tree.predict(X_train) # predict -> devuelve las clases: 0 o 1
y_pred_test_dt = decision_tree.predict(X_test)

In [52]:
y_pred_train_dt

array([1, 0, 0, ..., 0, 0, 1], shape=(35000,))

In [53]:
y_train

8319     1
7833     0
27390    0
44413    1
24218    0
        ..
48892    0
25727    0
18911    0
25680    0
43737    1
Name: target, Length: 35000, dtype: int64

In [54]:
from sklearn.metrics import classification_report

In [ ]:
# No es trivial la eleccion del mejor modelo en base a su performance, depende siempre del contexto de negocio y nuestro objetivo

In [55]:
# IMPORTANTE: SIEMPRE EVALUAR LA PERFORMANCE DE UN MODELO ENTRENADO POR UNO MISMO EN TODOS LOS CONJUNTOS
print("TRAIN")
print(classification_report(y_train, y_pred_train_dt))
print("--------------------------------------------------------")
print("TEST")
print(classification_report(y_test, y_pred_test_dt))

TRAIN
              precision    recall  f1-score   support

           0       0.81      0.76      0.78     22170
           1       0.62      0.70      0.66     12830

    accuracy                           0.73     35000
   macro avg       0.72      0.73      0.72     35000
weighted avg       0.74      0.73      0.74     35000

--------------------------------------------------------
TEST
              precision    recall  f1-score   support

           0       0.81      0.75      0.78      9501
           1       0.62      0.70      0.65      5499

    accuracy                           0.73     15000
   macro avg       0.71      0.72      0.72     15000
weighted avg       0.74      0.73      0.73     15000

In [48]:
# IMPORTANTE: SIEMPRE EVALUAR LA PERFORMANCE DE UN MODELO ENTRENADO POR UNO MISMO EN TODOS LOS CONJUNTOS
# performance con max_depth = 1 -> seguramente uso "gender" para predecir
print("TRAIN")
print(classification_report(y_train, y_pred_train_dt))
print("--------------------------------------------------------")
print("TEST")
print(classification_report(y_test, y_pred_test_dt))

TRAIN
              precision    recall  f1-score   support

           0       0.96      0.55      0.70     22170
           1       0.55      0.96      0.70     12830

    accuracy                           0.70     35000
   macro avg       0.75      0.75      0.70     35000
weighted avg       0.81      0.70      0.70     35000

--------------------------------------------------------
TEST
              precision    recall  f1-score   support

           0       0.96      0.55      0.70      9501
           1       0.55      0.96      0.70      5499

    accuracy                           0.70     15000
   macro avg       0.76      0.75      0.70     15000
weighted avg       0.81      0.70      0.70     15000

In [ ]:
# Cuando estan overfitteando -> una buena practica es reducir la "complejidad" del algoritmo para reducir el riesgo de overfitting.